import { PermissionRow } from './permission-model';
const DELETE = [
  {
    workspaceId: 0,
    action: 'Delete Daphne Walton',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 1,
    action: 'Delete Sargent Anthony',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 2,
    action: 'Delete Rose Armstrong',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 3,
    action: 'Delete Sheri Ramsey',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 4,
    action: 'Delete Green Cleveland',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 5,
    action: 'Delete Wynn Albert',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 6,
    action: 'Delete Judith Carroll',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 7,
    action: 'Delete Rosa Spence',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 8,
    action: 'Delete Emilia Byrd',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 9,
    action: 'Delete Beasley West',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 10,
    action: 'Delete Terra Schroeder',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 11,
    action: 'Delete Gross Hull',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 12,
    action: 'Delete Doyle Santos',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 13,
    action: 'Delete Petersen Dorsey',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 14,
    action: 'Delete Bridget Holcomb',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 15,
    action: 'Delete Malone Dale',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 16,
    action: 'Delete Harding Gordon',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 17,
    action: 'Delete Lloyd Randolph',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 18,
    action: 'Delete Johnnie Mcknight',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 19,
    action: 'Delete Winters Haley',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 20,
    action: 'Delete Barlow Johns',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
];
const ADD = [
  {
    workspaceId: 0,
    action: 'Add James Robles',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 1,
    action: 'Add Ferrell Munoz',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 2,
    action: 'Add Cooper Dejesus',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 3,
    action: 'Add Margery Benton',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 4,
    action: 'Add Moreno Merritt',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 5,
    action: 'Add Candy Wolf',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 6,
    action: 'Add Georgia Maxwell',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 7,
    action: 'Add Iris Ballard',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 8,
    action: 'Add Downs Brooks',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
];
const VIEW = [
  {
    workspaceId: 0,
    action: 'Delete Adams Craft',
    actionCategory: 'VIEW',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 1,
    action: 'Delete Pierce Christensen',
    actionCategory: 'VIEW',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 2,
    action: 'Delete Ochoa Sexton',
    actionCategory: 'VIEW',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: 3,
    action: 'Delete Iris Franco',
    actionCategory: 'VIEW',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
];
export const DATA: PermissionRow[] = [
  ...DELETE,
  ...ADD,
  ...VIEW,
  {
    workspaceId: null,
    action: 'View Client Listing - All Clients',
    actionCategory: 'VIEW',
    admin: false,
    accountManager: false,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: null,
    action: 'View Client Details',
    actionCategory: 'VIEW',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: null,
    action: 'View Custom Details',
    actionCategory: 'VIEW',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: null,
    action: 'Add Legal Identifiers',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: null,
    action: 'Add Custom Identifiers',
    actionCategory: 'ADD',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: null,
    action: 'Delete Banking Information',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
  {
    workspaceId: null,
    action: 'Delete Custom Information',
    actionCategory: 'DELETE',
    admin: true,
    accountManager: true,
    head: true,
    lead: true,
    user: true,
    analyst: true,
  },
];
