export const data = [
  {
    workspaceId: null,
    module: 'CLIENT_LISTING',
    order: 1,
    role: 'Account Manager',
    roleKey: 'ACCOUNT_MANAGER',
    permissions: {
      VIEW : [
        {
          action: 'View Client Listing - All Clients',
          actionKey: 'VIEW_CLIENT_LISTING_ALL',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Client Details',
          actionKey: 'VIEW_CLIENT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Legal Identifiers',
          actionKey: 'VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Banking Information',
          actionKey: 'VIEW_BANKING_INFORMATION',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View User Contacts Details',
          actionKey: 'VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Files',
          actionKey: 'VIEW_FILES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Fee Arrangements',
          actionKey: 'VIEW_FEE_ARRANGEMENTS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Analytics',
          actionKey: 'VIEW_ANALYTICS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Invoices',
          actionKey: 'VIEW_INVOICES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Candidates Placed',
          actionKey: 'VIEW_CANDIDATES_PLACED',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Positions',
          actionKey: 'VIEW_POSITIONS',
          actionCategory: 'VIEW',
          value: true,
        }
      ],
      ADD:[
        {
          action: 'Add Client Details - Clients + Jobs',
          actionKey: 'ADD_CLIENT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Legal Identifiers',
          actionKey: 'ADD_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Banking Information',
          actionKey: 'ADD_VIEW_BANKING_INFORMATION',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add User Contacts Details- Clients + Jobs',
          actionKey: 'ADD_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Files',
          actionKey: 'ADD_FILES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Fee Arrangements',
          actionKey: 'ADD_FEE_ARRANGEMENTS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Invoices',
          actionKey: 'ADD_INVOICES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Candidates Placed',
          actionKey: 'ADD_CANDIDATES_PLACED',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Positions',
          actionKey: 'ADD_POSITIONS',
          actionCategory: 'ADD',
          value: true,
        }
      ],
      EDIT:[
        {
          action: 'Edit Client Details',
          actionKey: 'EDIT_CLIENT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Legal Identifiers',
          actionKey: 'EDIT_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Banking Information',
          actionKey: 'EDIT_VIEW_BANKING_INFORMATION',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit User Contacts Details',
          actionKey: 'EDIT_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Files',
          actionKey: 'EDIT_FILES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Fee Arrangements',
          actionKey: 'EDIT_FEE_ARRANGEMENTS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Invoices',
          actionKey: 'EDIT_INVOICES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Candidates Placed',
          actionKey: 'EDIT_CANDIDATES_PLACED',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Positions',
          actionKey: 'EDIT_POSITIONS',
          actionCategory: 'EDIT',
          value: true,
        }
      ],
      DELETE:[
        {
          action: 'Delete Client Details',
          actionKey: 'DELETE_CLIENT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Legal Identifiers',
          actionKey: 'DELETE_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Banking Information',
          actionKey: 'DELETE_VIEW_BANKING_INFORMATION',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete User Contacts Details',
          actionKey: 'DELETE_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Files',
          actionKey: 'DELETE_FILES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Fee Arrangements',
          actionKey: 'DELETE_FEE_ARRANGEMENTS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Invoices',
          actionKey: 'DELETE_INVOICES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Candidates Placed',
          actionKey: 'DELETE_CANDIDATES_PLACED',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Positions',
          actionKey: 'DELETE_POSITIONS',
          actionCategory: 'DELETE',
          value: true,
        }
      ],
    },
  },
  {
    workspaceId: null,
    module: 'CLIENT_LISTING',
    order: 2,
    role: 'Head',
    roleKey: 'HEAD',
    permissions: {
      VIEW : [
        {
          action: 'View Client Listing - All Clients',
          actionKey: 'VIEW_CLIENT_LISTING_ALL',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Client Details',
          actionKey: 'VIEW_CLIENT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Legal Identifiers',
          actionKey: 'VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Banking Information',
          actionKey: 'VIEW_BANKING_INFORMATION',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View User Contacts Details',
          actionKey: 'VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Files',
          actionKey: 'VIEW_FILES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Fee Arrangements',
          actionKey: 'VIEW_FEE_ARRANGEMENTS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Analytics',
          actionKey: 'VIEW_ANALYTICS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Invoices',
          actionKey: 'VIEW_INVOICES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Candidates Placed',
          actionKey: 'VIEW_CANDIDATES_PLACED',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Positions',
          actionKey: 'VIEW_POSITIONS',
          actionCategory: 'VIEW',
          value: true,
        }
      ],
      ADD:[
        {
          action: 'Add Client Details - Clients + Jobs',
          actionKey: 'ADD_CLIENT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Legal Identifiers',
          actionKey: 'ADD_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Banking Information',
          actionKey: 'ADD_VIEW_BANKING_INFORMATION',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add User Contacts Details- Clients + Jobs',
          actionKey: 'ADD_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Files',
          actionKey: 'ADD_FILES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Fee Arrangements',
          actionKey: 'ADD_FEE_ARRANGEMENTS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Invoices',
          actionKey: 'ADD_INVOICES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Candidates Placed',
          actionKey: 'ADD_CANDIDATES_PLACED',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Positions',
          actionKey: 'ADD_POSITIONS',
          actionCategory: 'ADD',
          value: true,
        }
      ],
      EDIT:[
        {
          action: 'Edit Client Details',
          actionKey: 'EDIT_CLIENT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Legal Identifiers',
          actionKey: 'EDIT_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Banking Information',
          actionKey: 'EDIT_VIEW_BANKING_INFORMATION',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit User Contacts Details',
          actionKey: 'EDIT_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Files',
          actionKey: 'EDIT_FILES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Fee Arrangements',
          actionKey: 'EDIT_FEE_ARRANGEMENTS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Invoices',
          actionKey: 'EDIT_INVOICES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Candidates Placed',
          actionKey: 'EDIT_CANDIDATES_PLACED',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Positions',
          actionKey: 'EDIT_POSITIONS',
          actionCategory: 'EDIT',
          value: true,
        }
      ],
      DELETE:[
        {
          action: 'Delete Client Details',
          actionKey: 'DELETE_CLIENT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Legal Identifiers',
          actionKey: 'DELETE_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Banking Information',
          actionKey: 'DELETE_VIEW_BANKING_INFORMATION',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete User Contacts Details',
          actionKey: 'DELETE_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Files',
          actionKey: 'DELETE_FILES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Fee Arrangements',
          actionKey: 'DELETE_FEE_ARRANGEMENTS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Invoices',
          actionKey: 'DELETE_INVOICES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Candidates Placed',
          actionKey: 'DELETE_CANDIDATES_PLACED',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Positions',
          actionKey: 'DELETE_POSITIONS',
          actionCategory: 'DELETE',
          value: true,
        }
      ],
    },
  },
  {
    workspaceId: null,
    module: 'CLIENT_LISTING',
    order: 3,
    role: 'Lead',
    roleKey: 'LEAD',
    permissions: {
      VIEW : [
        {
          action: 'View Client Listing - All Clients',
          actionKey: 'VIEW_CLIENT_LISTING_ALL',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Client Details',
          actionKey: 'VIEW_CLIENT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Legal Identifiers',
          actionKey: 'VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Banking Information',
          actionKey: 'VIEW_BANKING_INFORMATION',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View User Contacts Details',
          actionKey: 'VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Files',
          actionKey: 'VIEW_FILES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Fee Arrangements',
          actionKey: 'VIEW_FEE_ARRANGEMENTS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Analytics',
          actionKey: 'VIEW_ANALYTICS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Invoices',
          actionKey: 'VIEW_INVOICES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Candidates Placed',
          actionKey: 'VIEW_CANDIDATES_PLACED',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Positions',
          actionKey: 'VIEW_POSITIONS',
          actionCategory: 'VIEW',
          value: true,
        }
      ],
      ADD:[
        {
          action: 'Add Client Details - Clients + Jobs',
          actionKey: 'ADD_CLIENT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Legal Identifiers',
          actionKey: 'ADD_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Banking Information',
          actionKey: 'ADD_VIEW_BANKING_INFORMATION',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add User Contacts Details- Clients + Jobs',
          actionKey: 'ADD_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Files',
          actionKey: 'ADD_FILES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Fee Arrangements',
          actionKey: 'ADD_FEE_ARRANGEMENTS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Invoices',
          actionKey: 'ADD_INVOICES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Candidates Placed',
          actionKey: 'ADD_CANDIDATES_PLACED',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Positions',
          actionKey: 'ADD_POSITIONS',
          actionCategory: 'ADD',
          value: true,
        }
      ],
      EDIT:[
        {
          action: 'Edit Client Details',
          actionKey: 'EDIT_CLIENT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Legal Identifiers',
          actionKey: 'EDIT_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Banking Information',
          actionKey: 'EDIT_VIEW_BANKING_INFORMATION',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit User Contacts Details',
          actionKey: 'EDIT_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Files',
          actionKey: 'EDIT_FILES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Fee Arrangements',
          actionKey: 'EDIT_FEE_ARRANGEMENTS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Invoices',
          actionKey: 'EDIT_INVOICES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Candidates Placed',
          actionKey: 'EDIT_CANDIDATES_PLACED',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Positions',
          actionKey: 'EDIT_POSITIONS',
          actionCategory: 'EDIT',
          value: true,
        }
      ],
      DELETE:[
        {
          action: 'Delete Client Details',
          actionKey: 'DELETE_CLIENT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Legal Identifiers',
          actionKey: 'DELETE_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Banking Information',
          actionKey: 'DELETE_VIEW_BANKING_INFORMATION',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete User Contacts Details',
          actionKey: 'DELETE_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Files',
          actionKey: 'DELETE_FILES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Fee Arrangements',
          actionKey: 'DELETE_FEE_ARRANGEMENTS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Invoices',
          actionKey: 'DELETE_INVOICES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Candidates Placed',
          actionKey: 'DELETE_CANDIDATES_PLACED',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Positions',
          actionKey: 'DELETE_POSITIONS',
          actionCategory: 'DELETE',
          value: true,
        }
      ],
    },,
  },
  {
    workspaceId: null,
    module: 'CLIENT_LISTING',
    order: 4,
    role: 'User',
    roleKey: 'USER',
    permissions: {
      VIEW : [
        {
          action: 'View Client Listing - All Clients',
          actionKey: 'VIEW_CLIENT_LISTING_ALL',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Client Details',
          actionKey: 'VIEW_CLIENT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Legal Identifiers',
          actionKey: 'VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Banking Information',
          actionKey: 'VIEW_BANKING_INFORMATION',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View User Contacts Details',
          actionKey: 'VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Files',
          actionKey: 'VIEW_FILES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Fee Arrangements',
          actionKey: 'VIEW_FEE_ARRANGEMENTS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Analytics',
          actionKey: 'VIEW_ANALYTICS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Invoices',
          actionKey: 'VIEW_INVOICES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Candidates Placed',
          actionKey: 'VIEW_CANDIDATES_PLACED',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Positions',
          actionKey: 'VIEW_POSITIONS',
          actionCategory: 'VIEW',
          value: true,
        }
      ],
      ADD:[
        {
          action: 'Add Client Details - Clients + Jobs',
          actionKey: 'ADD_CLIENT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Legal Identifiers',
          actionKey: 'ADD_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Banking Information',
          actionKey: 'ADD_VIEW_BANKING_INFORMATION',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add User Contacts Details- Clients + Jobs',
          actionKey: 'ADD_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Files',
          actionKey: 'ADD_FILES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Fee Arrangements',
          actionKey: 'ADD_FEE_ARRANGEMENTS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Invoices',
          actionKey: 'ADD_INVOICES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Candidates Placed',
          actionKey: 'ADD_CANDIDATES_PLACED',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Positions',
          actionKey: 'ADD_POSITIONS',
          actionCategory: 'ADD',
          value: true,
        }
      ],
      EDIT:[
        {
          action: 'Edit Client Details',
          actionKey: 'EDIT_CLIENT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Legal Identifiers',
          actionKey: 'EDIT_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Banking Information',
          actionKey: 'EDIT_VIEW_BANKING_INFORMATION',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit User Contacts Details',
          actionKey: 'EDIT_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Files',
          actionKey: 'EDIT_FILES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Fee Arrangements',
          actionKey: 'EDIT_FEE_ARRANGEMENTS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Invoices',
          actionKey: 'EDIT_INVOICES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Candidates Placed',
          actionKey: 'EDIT_CANDIDATES_PLACED',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Positions',
          actionKey: 'EDIT_POSITIONS',
          actionCategory: 'EDIT',
          value: true,
        }
      ],
      DELETE:[
        {
          action: 'Delete Client Details',
          actionKey: 'DELETE_CLIENT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Legal Identifiers',
          actionKey: 'DELETE_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Banking Information',
          actionKey: 'DELETE_VIEW_BANKING_INFORMATION',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete User Contacts Details',
          actionKey: 'DELETE_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Files',
          actionKey: 'DELETE_FILES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Fee Arrangements',
          actionKey: 'DELETE_FEE_ARRANGEMENTS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Invoices',
          actionKey: 'DELETE_INVOICES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Candidates Placed',
          actionKey: 'DELETE_CANDIDATES_PLACED',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Positions',
          actionKey: 'DELETE_POSITIONS',
          actionCategory: 'DELETE',
          value: true,
        }
      ],
    },
  },
  {
    workspaceId: null,
    module: 'CLIENT_LISTING',
    order: 5,
    role: 'Analyst',
    roleKey: 'ANALYST',
    permissions: {
      VIEW : [
        {
          action: 'View Client Listing - All Clients',
          actionKey: 'VIEW_CLIENT_LISTING_ALL',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Client Details',
          actionKey: 'VIEW_CLIENT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Legal Identifiers',
          actionKey: 'VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Banking Information',
          actionKey: 'VIEW_BANKING_INFORMATION',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View User Contacts Details',
          actionKey: 'VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Files',
          actionKey: 'VIEW_FILES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Fee Arrangements',
          actionKey: 'VIEW_FEE_ARRANGEMENTS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Analytics',
          actionKey: 'VIEW_ANALYTICS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Invoices',
          actionKey: 'VIEW_INVOICES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Candidates Placed',
          actionKey: 'VIEW_CANDIDATES_PLACED',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Positions',
          actionKey: 'VIEW_POSITIONS',
          actionCategory: 'VIEW',
          value: true,
        }
      ],
      ADD:[
        {
          action: 'Add Client Details - Clients + Jobs',
          actionKey: 'ADD_CLIENT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Legal Identifiers',
          actionKey: 'ADD_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Banking Information',
          actionKey: 'ADD_VIEW_BANKING_INFORMATION',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add User Contacts Details- Clients + Jobs',
          actionKey: 'ADD_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Files',
          actionKey: 'ADD_FILES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Fee Arrangements',
          actionKey: 'ADD_FEE_ARRANGEMENTS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Invoices',
          actionKey: 'ADD_INVOICES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Candidates Placed',
          actionKey: 'ADD_CANDIDATES_PLACED',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Positions',
          actionKey: 'ADD_POSITIONS',
          actionCategory: 'ADD',
          value: true,
        }
      ],
      EDIT:[
        {
          action: 'Edit Client Details',
          actionKey: 'EDIT_CLIENT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Legal Identifiers',
          actionKey: 'EDIT_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Banking Information',
          actionKey: 'EDIT_VIEW_BANKING_INFORMATION',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit User Contacts Details',
          actionKey: 'EDIT_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Files',
          actionKey: 'EDIT_FILES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Fee Arrangements',
          actionKey: 'EDIT_FEE_ARRANGEMENTS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Invoices',
          actionKey: 'EDIT_INVOICES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Candidates Placed',
          actionKey: 'EDIT_CANDIDATES_PLACED',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Positions',
          actionKey: 'EDIT_POSITIONS',
          actionCategory: 'EDIT',
          value: true,
        }
      ],
      DELETE:[
        {
          action: 'Delete Client Details',
          actionKey: 'DELETE_CLIENT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Legal Identifiers',
          actionKey: 'DELETE_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Banking Information',
          actionKey: 'DELETE_VIEW_BANKING_INFORMATION',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete User Contacts Details',
          actionKey: 'DELETE_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Files',
          actionKey: 'DELETE_FILES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Fee Arrangements',
          actionKey: 'DELETE_FEE_ARRANGEMENTS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Invoices',
          actionKey: 'DELETE_INVOICES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Candidates Placed',
          actionKey: 'DELETE_CANDIDATES_PLACED',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Positions',
          actionKey: 'DELETE_POSITIONS',
          actionCategory: 'DELETE',
          value: true,
        }
      ],
    },
  },
  {
    workspaceId: null,
    module: 'CLIENT_LISTING',
    order: 6,
    role: 'Admin',
    roleKey: 'ADMIN',
    permissions: {
      VIEW : [
        {
          action: 'View Client Listing - All Clients',
          actionKey: 'VIEW_CLIENT_LISTING_ALL',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Client Details',
          actionKey: 'VIEW_CLIENT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Legal Identifiers',
          actionKey: 'VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Banking Information',
          actionKey: 'VIEW_BANKING_INFORMATION',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View User Contacts Details',
          actionKey: 'VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Files',
          actionKey: 'VIEW_FILES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Fee Arrangements',
          actionKey: 'VIEW_FEE_ARRANGEMENTS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Analytics',
          actionKey: 'VIEW_ANALYTICS',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Invoices',
          actionKey: 'VIEW_INVOICES',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Candidates Placed',
          actionKey: 'VIEW_CANDIDATES_PLACED',
          actionCategory: 'VIEW',
          value: true,
        },
        {
          action: 'View Positions',
          actionKey: 'VIEW_POSITIONS',
          actionCategory: 'VIEW',
          value: true,
        }
      ],
      ADD:[
        {
          action: 'Add Client Details - Clients + Jobs',
          actionKey: 'ADD_CLIENT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Legal Identifiers',
          actionKey: 'ADD_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add View Banking Information',
          actionKey: 'ADD_VIEW_BANKING_INFORMATION',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add User Contacts Details- Clients + Jobs',
          actionKey: 'ADD_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Files',
          actionKey: 'ADD_FILES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Fee Arrangements',
          actionKey: 'ADD_FEE_ARRANGEMENTS',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Invoices',
          actionKey: 'ADD_INVOICES',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Candidates Placed',
          actionKey: 'ADD_CANDIDATES_PLACED',
          actionCategory: 'ADD',
          value: true,
        },
        {
          action: 'Add Positions',
          actionKey: 'ADD_POSITIONS',
          actionCategory: 'ADD',
          value: true,
        }
      ],
      EDIT:[
        {
          action: 'Edit Client Details',
          actionKey: 'EDIT_CLIENT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Legal Identifiers',
          actionKey: 'EDIT_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit View Banking Information',
          actionKey: 'EDIT_VIEW_BANKING_INFORMATION',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit User Contacts Details',
          actionKey: 'EDIT_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Files',
          actionKey: 'EDIT_FILES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Fee Arrangements',
          actionKey: 'EDIT_FEE_ARRANGEMENTS',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Invoices',
          actionKey: 'EDIT_INVOICES',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Candidates Placed',
          actionKey: 'EDIT_CANDIDATES_PLACED',
          actionCategory: 'EDIT',
          value: true,
        },
        {
          action: 'Edit Positions',
          actionKey: 'EDIT_POSITIONS',
          actionCategory: 'EDIT',
          value: true,
        }
      ],
      DELETE:[
        {
          action: 'Delete Client Details',
          actionKey: 'DELETE_CLIENT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Legal Identifiers',
          actionKey: 'DELETE_VIEW_LEGAL_IDENTIFIERS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete View Banking Information',
          actionKey: 'DELETE_VIEW_BANKING_INFORMATION',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete User Contacts Details',
          actionKey: 'DELETE_VIEW_USER_CONTACT_DETAILS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Files',
          actionKey: 'DELETE_FILES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Fee Arrangements',
          actionKey: 'DELETE_FEE_ARRANGEMENTS',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Invoices',
          actionKey: 'DELETE_INVOICES',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Candidates Placed',
          actionKey: 'DELETE_CANDIDATES_PLACED',
          actionCategory: 'DELETE',
          value: true,
        },
        {
          action: 'Delete Positions',
          actionKey: 'DELETE_POSITIONS',
          actionCategory: 'DELETE',
          value: true,
        }
      ],
    },
  },
];
